field.storage_settings.isced_f:
  type: mapping
  label: ISCED-F field of study storage settings
  mapping:
    foo:
      type: string
      label: Foo

field.field_settings.isced_f:
  type: mapping
  label: ISCED-F field of study field settings
  mapping:
    bar:
      type: string
      label: Bar

field.value.isced_f:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.isced_f_select:
  type: mapping
  label: ISCED-F select list widget settings
  mapping:
    foo:
      type: string
      label: Foo

field.formatter.settings.isced_f_default:
  type: mapping
  label: ISCED-F default formatter settings
  mapping:
    foo:
      type: string
      label: Foo
