field.value.isced_f:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.isced_f_select:
  type: mapping
  label: ISCED-F select list widget settings
  mapping:
    allow_all_levels:
      type: boolean
      label: 'Allow all levels of selection'

field.formatter.settings.isced_f_default:
  type: mapping
  label: ISCED-F default formatter settings
  mapping:
    prefix:
      type: boolean
      label: 'Prefix the study field label with its ISCED-F code'
